language: r
cache: packages
os: linux
dist: xenial

r:
  - oldrel
  - release
  - devel

apt_packages:
  - libgsl0-dev
  - devscripts

r_packages:
  - devtools
  - covr


after_success:
  - Rscript -e 'covr::codecov()'
