# Sample .travis.yml for R projects.
#
# See https://github.com/craigcitro/r-travis
#     https://github.com/eddelbuettel/r-travis/

sudo: required

language: c

before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_aptget libgsl0-dev r-cran-rcpp
  - R --slave -e 'install.packages("RcppGSL", repo="http://ghrr.github.io/drat")'

script:
- ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
email:
on_success: change
on_failure: change

